apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Simple Pipeline

on:
  push:
    branches:
      - 'stop'

jobs:
  build:
    steps:
      - name: Build
        uses: docker://ubuntu:latest
        shell: bash
        run: |
          echo "Building the project..."
          # Add your build commands here

  test:
    needs: build
    steps:
      - name: Test
        uses: docker://ubuntu:latest
        shell: bash
        run: |
          echo "Running tests..."
          # Add your test commands here

  deploy:
    needs: test
    steps:
      - name: Deploy
        uses: docker://ubuntu:latest
        shell: bash
        run: |
          echo "Deploying the project..."
          # Add your deployment commands here
