apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Web UI Test Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  test:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Set up Python
        uses: docker://python:3.9
        shell: bash
        run: |
          python --version
          pip install --upgrade pip

      - name: Pull Selenium Chrome image
        uses: docker://ubuntu:latest
        shell: bash
        run: |
          docker pull selenium/standalone-chrome:latest

      - name: Start Selenium container
        uses: docker://ubuntu:latest
        shell: bash
        run: |
          docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" --name selenium_chrome selenium/standalone-chrome:latest

      - name: Install dependencies
        uses: docker://python:3.9
        shell: bash
        run: |
          pip install selenium pytest

      - name: Run tests
        uses: docker://python:3.9
        shell: bash
        run: |
          pytest test_web_interface.py

      - name: Clean up
        uses: docker://ubuntu:latest
        shell: bash
        run: |
          docker stop selenium_chrome
          docker rm selenium_chrome