apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Simple CI/CD Demo

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Set up Go
        uses: docker://golang:1.17
        shell: bash
        run: |
          go version
          go env

      - name: Initialize Go module
        uses: docker://golang:1.17
        shell: bash
        run: |
          go mod init myproject
          go mod tidy

      - name: Build
        uses: docker://golang:1.17
        shell: bash
        run: |
          go build -v ./...

  lint:
    needs: build
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Initialize Go module
        uses: docker://golang:1.17
        shell: bash
        run: |
          go mod init myproject
          go mod tidy

      - name: Run golangci-lint
        uses: docker://golangci/golangci-lint:v1.43
        shell: bash
        run: |
          golangci-lint run

  test:
    needs: build
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Initialize Go module
        uses: docker://golang:1.17
        shell: bash
        run: |
          go mod init myproject
          go mod tidy

      - name: Run tests
        uses: docker://golang:1.17
        shell: bash
        run: |
          go test -v ./...

  simulate-deploy:
    needs: [test, lint]
    steps:
      - name: Simulate deployment
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "Simulating deployment to development environment"
          echo "Application version: ${CLOUDBEES_WORKFLOW_ID:-UNKNOWN}"
          echo "Deployment successful!"

  notify:
    needs: simulate-deploy
    steps:
      - name: Send notification
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "Sending notification..."
          echo "Deployment completed successfully at $(date)"